projectmanager/app/urls.py
from django.urls import path, include
from app import views

urlpatterns = [
    path('', views.Homepage.as_view(), name="index"),
    path('tinymce/', include('tinymce.urls')),
    path('login/', views.Login, name="login"),
    path('facultyRegister/', views.facultyRegistration,
         name="facultyRegistration"),
    path('studentRegister/', views.studentRegistration,
         name="studentRegistration"),
    path('studentdash/', views.StudentDashboard, name="studentDashboard"),
    path('facultydash/', views.facultyDashboard, name="facultyDashboard"),
    path('projectsynopsis/', views.projectSynopsisCreation, name="projectsynopsis"),
    path('projectphase1/', views.projectPhase1Creation, name="projectphase1"),
    path('projectphase2/', views.projectPhase2Creation, name="projectphase2"),
    path('projectfianle/', views.projectFinaleCreation, name="projectfinale"),
    path('teams/', views.teamCreation, name="teams"),
    path('projectsynopsis/synopsisUpdate/<int:pk>', views.SynopsisUpdateView.as_view(), name="updateSynopsis"),
    path('projectphase1/phase1Update/<int:pk>', views.Phase1UpdateView.as_view(), name="updatePhase1"),
    path('projectphase2/phase2Update/<int:pk>', views.Phase2UpdateView.as_view(), name="updatePhase2"),
    path('projectfinale/finaleUpdate/<int:pk>', views.FinalUpdateView.as_view(), name="updateFinale"),
    path('facultyCommentSynopsis/<int:teamId>', views.facultyCommentSynopsis, name="facultyCommentSynopsis"),
    path('facultyCommentPhase1/<int:teamId>', views.facultyCommentPhase1, name="facultyCommentPhase1"),
    path('facultyCommentPhase2/<int:teamId>', views.facultyCommentPhase2, name="facultyCommentPhase2"),
    path('facultyCommentFinale/<int:teamId>', views.facultyCommentFinalPhase, name="facultyCommentFinale"),
    path('facultyViewLogs/<int:teamId>', views.facultyViewLogs, name="facultyViewLogs"),
    path('logout/', views.logout, name="logout"),
]

projectmanager/projectmanager/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

# Customizing admin texts
admin.site.site_header = 'Project Record Manager'
admin.site.index_title = 'Admin Dashboard'
admin.site.site_title = 'ProjectRecordManager'

projectmanager/app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from tinymce.models import HTMLField
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager, PermissionsMixin)


class UserManager(BaseUserManager):

    def create_user(self, email, password, is_active=True, is_staff=False, is_superuser=False,
                    is_student=False, is_faculty=False, is_faculty_available=False, is_student_available=False,
                    **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.admin = is_superuser
        user.active = is_active
        user.staff = is_staff
        user.isstudent = is_student
        user.isfaculty = is_faculty
        user.student_available = is_student_available
        user.faculty_available = is_faculty_available
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = None
    first_name = None
    last_name = None
    admin = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    isstudent = models.BooleanField(default=False)
    isfaculty = models.BooleanField(default=False)
    student_available = models.BooleanField(default=False)
    faculty_available = models.BooleanField(default=False)
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

    def __str__(self):
        return self.email

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_active(self):
        return self.active

    @property
    def is_superuser(self):
        return self.admin

    @property
    def is_student(self):
        return self.isstudent

    @property
    def is_faculty(self):
        return self.isfaculty

    @property
    def is_faculty_available(self):
        return self.faculty_available

    @property
    def is_student_available(self):
        return self.student_available


class Faculty(CustomUser):
    phone = models.CharField(max_length=11, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['phone']

    objects = UserManager()

    def __str__(self):
        return self.name + ' ' + self.email

    class Meta:
        db_table = "faculty"


class Batch(models.Model):
    batch_name = models.CharField(max_length=10)

    def __str__(self):
        return self.batch_name


class Student(CustomUser):
    usn = models.CharField(max_length=15, null=True, unique=True, default='1R')
    phone = models.CharField(max_length=11, null=True)
    section = models.CharField(max_length=5, null=True)
    batch = models.ForeignKey(Batch, on_delete=models.CASCADE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['usn', 'phone']

    objects = UserManager()

    def __str__(self):
        return self.name + ' ' + self.email

    class Meta:
        db_table = "student"


class Team(models.Model):
    owner = models.CharField(max_length=555, unique=True)
    partner = models.OneToOneField(
        Student, on_delete=models.CASCADE, null=True, blank=True, unique=True)
    guide = models.ForeignKey(
        Faculty, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=555, null=True, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "team"

    def __str__(self):
        return str(self.title) + ", Student1:  " + str(self.owner) + ", student2:  " + str(
            self.partner) + ", Guide:  " + str(self.guide)


class ProjectSynopsis(models.Model):
    scrum_master = models.CharField(max_length=100, default="scrum master")
    project_title = models.ForeignKey(
        Team, on_delete=models.CASCADE, null=True)
    synopsis = HTMLField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.project_title) + "synopsis"


class ProjectPhase1(models.Model):
    scrum_master = models.CharField(max_length=100, default="scrum master")
    project_title = models.ForeignKey(
        Team, on_delete=models.CASCADE, null=True)
    phase1 = HTMLField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.project_title) + "phase1"


class ProjectPhase2(models.Model):
    scrum_master = models.CharField(max_length=100, default="scrum master")
    project_title = models.ForeignKey(
        Team, on_delete=models.CASCADE, null=True)
    phase2 = HTMLField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.project_title) + "phase2"


class ProjectFinale(models.Model):
    scrum_master = models.CharField(max_length=100, default="scrum master")
    project_title = models.ForeignKey(
        Team, on_delete=models.CASCADE, null=True)
    finale = HTMLField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.project_title) + "finale"


class Logs(models.Model):
    logs_by = models.CharField(max_length=100, default="logs")
    tid = models.ForeignKey(
        Team, on_delete=models.CASCADE, null=True)
    description = models.CharField(max_length=500, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.logs_by)

projectmanager/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content="Project Record Manager"/>
    <meta name="author" content="Astrid"/>
    {% block title %} <title></title> {% endblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
    {% block useCss %} {% endblock %}
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"
            crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"/>
</head>

<body>
<!--  Navbar start-->
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'index' %}"
               style="text-decoration: none; color:royalblue; font-family: Verdana, Geneva, Tahoma, sans-serif;">
                <img src="{% static 'images/logo/logo2.png' %}" alt="logo" width="30px" class="img img-fluid"/>
                PROJECT RECORD MANAGER</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="nav navbar-nav">
                <li class="nav-item mr-3">
                    {% if request.user.is_student %}
                        <h5 style="text-decoration: none; color:royalblue;">{{ user.name }}</h5>
                    {% endif %}

                    {% if request.user.is_faculty %}
                        <h5 style="text-decoration: none; color:royalblue;">{{ user.name }}</h5>
                    {% endif %}
                </li>
                <li class="nav-item">
                    {% if request.user.is_student %}
                        <li class="nav-item">
                            <a class="mr-3" href="{% url 'studentDashboard' %}"
                               style="text-decoration: none; color:royalblue;">
                                <span class="fas fa-columns"></span>&nbsp;Dashboard
                            </a>
                        </li>
                    {% endif %}
                {% if request.user.is_faculty %}
                    <li class="nav-item">
                        <a class="mr-3" href="{% url 'facultyDashboard' %}" style="text-decoration: none; color:royalblue;">
                            <span class="fas fa-columns"></span>&nbsp;Dashboard
                        </a>
                    </li>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <a class="mr-2" href="{% url 'logout' %}" style="text-decoration: none; color:royalblue;">
                        <span class="fas fa-sign-out-alt"></span>&nbsp;Logout
                    </a>
                    </li>


                    <li class="nav-item">
                        {% else %}
                        <a class="mr-3" href="{% url 'login' %}" style="text-decoration: none; color:royalblue;">
                            <span class="fas fa-sign-in-alt"></span>&nbsp;Login
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="mr-3" href="{% url 'facultyRegistration' %}"
                           style="text-decoration: none; color:royalblue;">
                            <span class="fas fa-plus"></span>&nbsp;Faculty
                        </a>
                    </li>
                    <li class="nav-item">
                    <a class="" href="{% url 'studentRegistration' %}"
                       style="text-decoration: none; color: royalblue">
                        <span class="fas fa-plus"></span>&nbsp;Student
                    </a>
                {% endif %}
                </li>
            </ul>
        </div>
    </div>

</nav>


<!-- navbar end -->
<!-- main block -->
{% block content %}

{% endblock %}
<!--  main block end  -->

<br>

<footer class="container-fluid bg-dark p-2 fixed-bottom">
    <div class="row">
        <div class="col-md-6">
            <a href="{% url 'index' %}"><span class="fas fa-home"></span>&nbsp;Home</a> &nbsp;
            <a href="#"><span class="fas fa-book-open"></span>&nbsp;Testimonials</a>
        </div>
        <div class="col-md-6 text-right text-white">
            <span>© Copyright MCA RVCE 2020</span>
        </div>
    </div>
</footer>

<!-- <div class="row mb-0">
        <div class="col-7 col-sm-8 ml-4 text-center" style="border-right:1px dashed white ;">
            <h5 class="text-white">Links</h5>
            <ul class="list-unstyled">
                <li><a href="#"><span class="fas fa-home"></span>&nbsp;Home</a></li>
                <li><a href="#"><span class="fas fa-info-circle"></span>&nbsp;About Us</a></li>
                <li><a href="#"><span class="fas fa-address-book"></span>&nbsp;Contact Us</a></li>
                <li><a href="#"><span class="fas fa-book-open"></span>&nbsp;Testimonials</a></li>
            </ul>

        </div>
        <div class="col-4 col-sm-3 text-white">
            <p>© Copyright MCA RVCE 2020</p>
        </div>
    </div> -->

<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>

</body>

</html>

projectmanager/templates/faculty_dashboard.html
{% extends 'base.html' %}

{% block title %} <title>Faculty Dashboard</title> {% endblock %}

{% block useCss %} {% endblock %}

{% block content %}
    <div class="container-fluid mt-3">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header text-center font-weight-bold" style="background:powderblue; color:black;">
                        TEAM LIST
                    </div>
                    <div class="card-body">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <table class="table table-active table-responsive table-borderless">
                            <thead>
                            <tr>
                                <th>Project Title</th>
                                <th>Student 1</th>
                                <th>Student 2</th>
                                <th>Synopsis</th>
                                <th>Phase 1</th>
                                <th>Phase 2</th>
                                <th>Final Phase</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for data in team %}
                                <tr>
                                    <td>{{ data.title }}</td>
                                    <td>{{ data.owner }}</td>
                                    <td>{{ data.partner }}</td>
                                    <td>
                                        <a href="{% url 'facultyCommentSynopsis' data.id %}"
                                           class="btn btn-info text-decoration-none">Synopsis</a>
                                    </td>
                                    <td>
                                        <a href="{% url 'facultyCommentPhase1' data.id %}"
                                           class="btn btn-info text-decoration-none">Phase 1</a>
                                    </td>
                                    <td>
                                        <a href="{% url 'facultyCommentPhase2' data.id %}"
                                           class="btn btn-info text-decoration-none">Phase 2</a>
                                    </td>
                                    <td>
                                        <a href="{% url 'facultyCommentFinale' data.id %}"
                                           class="btn btn-info text-decoration-none">Final Phase</a>
                                    </td>
                                    <td>
                                        <a href="{% url 'facultyViewLogs' data.id %}"
                                           class="btn btn-info text-decoration-none">Logs</a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                        {#                    {% for data in docx %}#}
                        {#                        {{ data }}#}
                        {#                    {% endfor %}#}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

projectmanager/templates/faculty_register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %} <title>Index</title> {% endblock %}

{% block useCss %} {% endblock %}

{% block content %}
<div class="container p-1">
    <div class="card">
        <div class="card-header">
            <h4>Faculty Registration</h4>
        </div>
        <div class="card-body mx-auto">
            <form action="{% url 'facultyRegistration' %}" method="POST">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.email|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.phone|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12 mb-0">
                        {{ form.name|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.password1|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.password2|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4 mb-0">
                        <button type="submit" class="btn rounded-pill btn-block font-weight-bold"
                            style="background: #29a7a6 ">Register User
                        </button>
                    </div>
                    <div class="form-group col-md-6 mx-auto">
                        <div class="mt-2">
                            <small class="text-muted">
                                Do you need an account? <a class="text-danger" href="{% url 'login' %}">Sign
                                    In</a>
                            </small>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>


</div>

{% endblock %}

projectmanager/templates/kanban.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

projectmanager/templates/profile.html
{% extends 'base.html' %}

{% block title %} <title>Index</title> {% endblock %}

{% block useCss %}
<link rel="stylesheet" href="{% static 'css/main.css' %}" />
{% endblock %}

{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        <div class="col-md-6 text-left offset-md-3">
            <div class="card">
                <div class="card-header font-weight-bold " style="background:powderblue; color:black">INSTRUCTIONS</div>
                <div class="card-body">

                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

projectmanager/templates/student_dashboard.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %} <title>Student Dashboard</title>
    {{ form.media }}
    <script type="text/javascript" src="{% static 'tinymce/tinymce.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'django_tinymce/init_tinymce.js' %}"></script>
{% endblock %}


{% block useCss %} {% endblock %}

{% block content %}
    <div class="container-fluid mt-3">
        <div class="row mb-3">

            <div class="col-md-8 text-left">
                <div class="card">
                    <div class="card-header font-weight-bold " style="background:powderblue; color:black">Create Log :
                    </div>
                    <div class="card-body">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}

                        {% if forml %}
                            <form method="POST" action="">
                                {% csrf_token %}
                                <div id="div_id_logs_by" class="form-group">
                                    <label for="id_logs_by" class=" requiredField">
                                        Logs by<span class="asteriskField">*</span>
                                    </label>
                                    <div class="">
                                        <input type="text" name="logs_by" value="{{ request.user.name }}"
                                               maxlength="100"
                                               class="textinput textInput form-control" id="id_logs_by" readonly>
                                    </div>
                                </div>
                                {#                            {{ forml.logs_by| as_crispy_field }}#}
                                {{ forml.tid| as_crispy_field }}
                                {{ forml.description| as_crispy_field }}
                                <button type="submit" class="btn btn-info"> Create</button>
                            </form>
                        {% else %}
                            <h4 class="text-danger">{{ ret }}</h4>
                        {% endif %}
                    </div>
                </div>
                <hr>
                <div class="card">
                    <div class="card-header font-weight-bold " style="background:powderblue; color:black">LOGS :</div>
                    <div class="card-body">

                        <table class="table table-borderless">
                            <thead>
                            <tr>
                                <th>Created By</th>
                                <th>Description</th>
                                <th>Updated At</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for data in idt %}
                                <tr>
                                    <td>{{ data.logs_by }}</td>
                                    <td>{{ data.description }}</td>
                                    <td>{{ data.updated_at }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>

            <div class="col-md-3 mx-auto ">
                <div class="card">
                    <div class="card-header text-center font-weight-bold" style="background:powderblue; color:black;">
                        QUICK
                        LINKS
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled">
                            <li><a href="{% url 'teams' %}" class="btn btn-danger btn-md"
                                   style="text-decoration: none;">Create
                                Team</a></li>
                            <li><a href="{% url 'index' %}" style="text-decoration: none; color:royalblue;">
                                <em class="fas fa-home"></em> Home</a></li>
                            <li><a href="{% url 'projectsynopsis' %}" style="text-decoration: none; color:royalblue;">
                                <em class="fas fa-file"></em> Synopsis</a></li>
                            <li><a href="{% url 'projectphase1' %}" style="text-decoration: none; color:royalblue;">
                                <em class="fas fa-file"></em> Phase - I</a></li>
                            <li><a href="{% url 'projectphase2' %}" style="text-decoration: none; color:royalblue;">
                                <em class="fas fa-file"></em> Phase - II</a></li>
                            <li><a href="{% url 'projectfinale' %}" style="text-decoration: none; color:royalblue;">
                                <em class="fas fa-file"></em> Final Phase</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

projectmanager/templates/team_create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %} <title>Team Creation</title>
{% endblock %}
{% block useCss %} {% endblock %}

{% block content %}

    <div class="container p-1">
        <div class="card mt-2">
            <div class="card-header font-weight-bold" style="background:powderblue; color:black;">
                TEAM
            </div>
            <div class="card-body">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <form action="{% url 'teams' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-12 mb-0">
                            <div id="div_id_owner" class="form-group">

                                <label for="id_owner" class=" requiredField">
                                    First Student<span class="asteriskField">*</span>
                                </label>

                                <div class="">
                                    <input type="text" name="owner" value="{{ user.name }} {{ user.email }}"
                                           class="form-control textinput textInput form-control"
                                           placeholder="First Student" maxlength="100" required="" id="id_owner" readonly>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12 mb-0">
                            {{ formt.partner|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12 mb-0">
                            {{ formt.guide|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12 mb-0">
                            {{ formt.title|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-8 mb-0 offset-2">
                            <button type="submit" class="btn btn-block font-weight-bold"
                                    style="background: royalblue;color: black; ">Submit Details
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>


    </div>

{% endblock %}