projectmanager/app/urls.py
from django.urls import path, include
from app import views

urlpatterns = [
    path('', views.Homepage.as_view(), name="index"),
    path('tinymce/', include('tinymce.urls')),
    path('login/', views.Login, name="login"),
    path('facultyRegister/', views.facultyRegistration,
         name="facultyRegistration"),
    path('studentRegister/', views.studentRegistration,
         name="studentRegistration"),
    path('studentdash/', views.StudentDashboard, name="studentDashboard"),
    path('facultydash/', views.facultyDashboard, name="facultyDashboard"),
    path('projectsynopsis/', views.projectSynopsisCreation, name="projectsynopsis"),
    path('projectphase1/', views.projectPhase1Creation, name="projectphase1"),
    path('projectphase2/', views.projectPhase2Creation, name="projectphase2"),
    path('projectfianle/', views.projectFinaleCreation, name="projectfinale"),
    path('teams/', views.teamCreation, name="teams"),
    path('projectsynopsis/synopsisUpdate/<int:pk>', views.SynopsisUpdateView.as_view(), name="updateSynopsis"),
    path('projectphase1/phase1Update/<int:pk>', views.Phase1UpdateView.as_view(), name="updatePhase1"),
    path('projectphase2/phase2Update/<int:pk>', views.Phase2UpdateView.as_view(), name="updatePhase2"),
    path('projectfinale/finaleUpdate/<int:pk>', views.FinalUpdateView.as_view(), name="updateFinale"),
    path('facultyCommentSynopsis/<int:teamId>', views.facultyCommentSynopsis, name="facultyCommentSynopsis"),
    path('facultyCommentPhase1/<int:teamId>', views.facultyCommentPhase1, name="facultyCommentPhase1"),
    path('facultyCommentPhase2/<int:teamId>', views.facultyCommentPhase2, name="facultyCommentPhase2"),
    path('facultyCommentFinale/<int:teamId>', views.facultyCommentFinalPhase, name="facultyCommentFinale"),
    path('facultyViewLogs/<int:teamId>', views.facultyViewLogs, name="facultyViewLogs"),
    path('logout/', views.logout, name="logout"),
]

projectmanager/projectmanager/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

# Customizing admin texts
admin.site.site_header = 'Project Record Manager'
admin.site.index_title = 'Admin Dashboard'
admin.site.site_title = 'ProjectRecordManager'

projectmanager/app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from tinymce.models import HTMLField
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager, PermissionsMixin)


class UserManager(BaseUserManager):

    def create_user(self, email, password, is_active=True, is_staff=False, is_superuser=False,
                    is_student=False, is_faculty=False, is_faculty_available=False, is_student_available=False,
                    **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.admin = is_superuser
        user.active = is_active
        user.staff = is_staff
        user.isstudent = is_student
        user.isfaculty = is_faculty
        user.student_available = is_student_available
        user.faculty_available = is_faculty_available
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = None
    first_name = None
    last_name = None
    admin = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    isstudent = models.BooleanField(default=False)
    isfaculty = models.BooleanField(default=False)
    student_available = models.BooleanField(default=False)
    faculty_available = models.BooleanField(default=False)
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

    def __str__(self):
        return self.email

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_active(self):
        return self.active

    @property
    def is_superuser(self):
        return self.admin

    @property
    def is_student(self):
        return self.isstudent

    @property
    def is_faculty(self):
        return self.isfaculty

    @property
    def is_faculty_available(self):
        return self.faculty_available

    @property
    def is_student_available(self):
        return self.student_available


class Faculty(CustomUser):
    phone = models.CharField(max_length=11, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['phone']

    objects = UserManager()

    def __str__(self):
        return self.name + ' ' + self.email

    class Meta:
        db_table = "faculty"


class Batch(models.Model):
    batch_name = models.CharField(max_length=10)

    def __str__(self):
        return self.batch_name


class Student(CustomUser):
    usn = models.CharField(max_length=15, null=True, unique=True, default='1R')
    phone = models.CharField(max_length=11, null=True)
    section = models.CharField(max_length=5, null=True)
    batch = models.ForeignKey(Batch, on_delete=models.CASCADE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['usn', 'phone']

    objects = UserManager()

    def __str__(self):
        return self.name + ' ' + self.email

    class Meta:
        db_table = "student"


class Team(models.Model):
    owner = models.CharField(max_length=555, unique=True)
    partner = models.OneToOneField(
        Student, on_delete=models.CASCADE, null=True, blank=True, unique=True)
    guide = models.ForeignKey(
        Faculty, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=555, null=True, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "team"

    def __str__(self):
        return str(self.title) + ", Student1:  " + str(self.owner) + ", student2:  " + str(
            self.partner) + ", Guide:  " + str(self.guide)


class ProjectSynopsis(models.Model):
    scrum_master = models.CharField(max_length=100, default="scrum master")
    project_title = models.ForeignKey(
        Team, on_delete=models.CASCADE, null=True)
    synopsis = HTMLField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.project_title) + "synopsis"


class ProjectPhase1(models.Model):
    scrum_master = models.CharField(max_length=100, default="scrum master")
    project_title = models.ForeignKey(
        Team, on_delete=models.CASCADE, null=True)
    phase1 = HTMLField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.project_title) + "phase1"


class ProjectPhase2(models.Model):
    scrum_master = models.CharField(max_length=100, default="scrum master")
    project_title = models.ForeignKey(
        Team, on_delete=models.CASCADE, null=True)
    phase2 = HTMLField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.project_title) + "phase2"


class ProjectFinale(models.Model):
    scrum_master = models.CharField(max_length=100, default="scrum master")
    project_title = models.ForeignKey(
        Team, on_delete=models.CASCADE, null=True)
    finale = HTMLField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.project_title) + "finale"


class Logs(models.Model):
    logs_by = models.CharField(max_length=100, default="logs")
    tid = models.ForeignKey(
        Team, on_delete=models.CASCADE, null=True)
    description = models.CharField(max_length=500, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.logs_by)

projectmanager/templates/project/commentFinalPhase.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} <title>Faculty View Final Phase</title>
    {{ form.media }}
    <script type="text/javascript" src="{% static 'tinymce/tinymce.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'django_tinymce/init_tinymce.js' %}"></script>
{% endblock %} {% block useCss %}

{% endblock %}

{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-body">
                {% if qs %}
                    <form method="POST">
                        <!-- Security token by Django -->
                        {% csrf_token %}
                        {% for data in qs %}
                            <div id="div_id_scrum_master" class="form-group">

                                <label for="id_scrum_master" class=" requiredField">
                                    Scrum master<span class="asteriskField">*</span>
                                </label>

                                <div class="">
                                    <input type="text" name="scrum_master" value="{{ data.scrum_master }}"
                                           maxlength="100"
                                           class="textinput textInput form-control" required="" id="id_scrum_master"
                                           readonly>
                                </div>
                            </div>
                            <div id="div_id_project_title" class="form-group">

                                <label for="id_project_title" class=" requiredField">
                                    Project title: <span class="badge p-2 m-1 font-weight-bolder"
                                                         style="color: black;background-color: powderblue;"> {{ data.project_title.title }}</span>
                                </label>


                                <div class="">
                                    <input type="text" name="project_title" class="form-control"
                                           value="{{ data.project_title.id }}" id="id_project_title" readonly hidden/>
                                </div>
                            </div>
                        {% endfor %}
                        {{ formc.finale|as_crispy_field }}

                        <div class="form-row">
                            <div class="form-group col-md-8 mb-0 offset-1">
                                <button type="submit" class="btn btn-block font-weight-bold"
                                        style="background: royalblue;color: black; ">Update Details
                                </button>
                            </div>
                        </div>

                    </form>
                {% else %}
                    <h4 class="text-danger">{{ ret }}</h4>
                {% endif %}
            </div>
        </div>
    </div>


{% endblock %}

projectmanager/templates/project/commentPhase1.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} <title>Faculty View Phase1</title>
    {{ form.media }}
    <script type="text/javascript" src="{% static 'tinymce/tinymce.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'django_tinymce/init_tinymce.js' %}"></script>
{% endblock %} {% block useCss %}

{% endblock %}

{% block content %}

    <div class="container">
        <div class="card">
            <div class="card-body">
                {% if qs %}
                    <form method="POST">
                        <!-- Security token by Django -->
                        {% csrf_token %}

                        {% for data in qs %}
                            <div id="div_id_scrum_master" class="form-group">

                                <label for="id_scrum_master" class=" requiredField">
                                    Scrum master<span class="asteriskField">*</span>
                                </label>

                                <div class="">
                                    <input type="text" name="scrum_master" value="{{ data.scrum_master }}"
                                           maxlength="100"
                                           class="textinput textInput form-control" required="" id="id_scrum_master"
                                           readonly>
                                </div>
                            </div>
                            <div id="div_id_project_title" class="form-group">

                                <label for="id_project_title" class=" requiredField">
                                    Project title: <span class="badge p-2 m-1 font-weight-bolder"
                                                         style="color: black;background-color: powderblue;"> {{ data.project_title.title }}</span>
                                </label>


                                <div class="">
                                    <input type="text" name="project_title" class="form-control"
                                           value="{{ data.project_title.id }}"
                                           id="id_project_title" readonly hidden/>
                                </div>
                            </div>
                        {% endfor %}
                        {{ formc.phase1|as_crispy_field }}

                        <div class="form-row">
                            <div class="form-group col-md-8 mb-0 offset-1">
                                <button type="submit" class="btn btn-block font-weight-bold"
                                        style="background: royalblue;color: black; ">Update Details
                                </button>
                            </div>
                        </div>

                    </form>
                {% else %}
                    <h4 class="text-danger">{{ ret }}</h4>
                {% endif %}

            </div>
        </div>
    </div>

{% endblock %}

projectmanager/templates/project/commentPhase2.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} <title>Faculty View Phase2</title>
    {{ form.media }}
    <script type="text/javascript" src="{% static 'tinymce/tinymce.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'django_tinymce/init_tinymce.js' %}"></script>
{% endblock %} {% block useCss %}

{% endblock %}

{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-body">
                {% if qs %}

                    <form method="POST">
                        <!-- Security token by Django -->
                        {% csrf_token %}
                        {% for data in qs %}
                            <div id="div_id_scrum_master" class="form-group">

                                <label for="id_scrum_master" class=" requiredField">
                                    Scrum master<span class="asteriskField">*</span>
                                </label>

                                <div class="">
                                    <input type="text" name="scrum_master" value="{{ data.scrum_master }}"
                                           maxlength="100"
                                           class="textinput textInput form-control" required="" id="id_scrum_master"
                                           readonly>
                                </div>
                            </div>
                            <div id="div_id_project_title" class="form-group">

                                <label for="id_project_title" class=" requiredField">
                                    Project title: <span class="badge p-2 m-1 font-weight-bolder"
                                                         style="color: black;background-color: powderblue;"> {{ data.project_title.title }}</span>
                                </label>


                                <div class="">
                                    <input type="text" name="project_title" class="form-control"
                                           value="{{ data.project_title.id }}" id="id_project_title" readonly hidden/>
                                </div>
                            </div>
                        {% endfor %}
                        {{ formc.phase2|as_crispy_field }}

                        <div class="form-row">
                            <div class="form-group col-md-8 mb-0 offset-1">
                                <button type="submit" class="btn btn-block font-weight-bold"
                                        style="background: royalblue;color: black; ">Update Details
                                </button>
                            </div>
                        </div>

                    </form>

                {% else %}
                    <h4 class="text-danger">{{ ret }}</h4>
                {% endif %}
            </div>
        </div>
    </div>



{% endblock %}

projectmanager/templates/project/commentSynopsis.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} <title>Faculty View Synopsis</title>
    {{ form.media }}
    <script type="text/javascript" src="{% static 'tinymce/tinymce.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'django_tinymce/init_tinymce.js' %}"></script>
{% endblock %} {% block useCss %}

{% endblock %}

{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-body">
                {% if qs %}

                    <form method="POST">
                        <!-- Security token by Django -->
                        {% csrf_token %}
                        {% for data in qs %}
                            <div id="div_id_scrum_master" class="form-group">

                                <label for="id_scrum_master" class=" requiredField">
                                    Scrum master<span class="asteriskField">*</span>
                                </label>

                                <div class="">
                                    <input type="text" name="scrum_master" value="{{ data.scrum_master }}"
                                           maxlength="100"
                                           class="textinput textInput form-control" required="" id="id_scrum_master"
                                           readonly>
                                </div>
                            </div>
                            <div id="div_id_project_title" class="form-group">

                                <label for="id_project_title" class=" requiredField">
                                    Project title: <span class="badge p-2 m-1 font-weight-bolder"
                                                         style="color: black;background-color: powderblue;"> {{ data.project_title.title }}</span>
                                </label>


                                <div class="">
                                    <input type="text" name="project_title" class="form-control"
                                           value="{{ data.project_title.id }}" id="id_project_title" readonly hidden/>
                                </div>
                            </div>
                        {% endfor %}
                        {{ formc.synopsis|as_crispy_field }}

                        <div class="form-row">
                            <div class="form-group col-md-8 mb-0 offset-1">
                                <button type="submit" class="btn btn-block font-weight-bold"
                                        style="background: royalblue;color: black; ">Update Details
                                </button>
                            </div>
                        </div>

                    </form>
                {% else %}
                    <h4 class="text-danger">{{ ret }}</h4>
                {% endif %}
            </div>
        </div>
    </div>


{% endblock %}

projectmanager/templates/project/project_finale.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %} <title>Synopsis</title>
    {{ form.media }}
    <script type="text/javascript" src="{% static 'tinymce/tinymce.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'django_tinymce/init_tinymce.js' %}"></script>
{% endblock %}


{% block useCss %} {% endblock %}

{% block content %}

    <div class="container p-1">
        <div class="card mt-2">
            <div class="card-header font-weight-bold" style="background:powderblue; color:black;">
                PROJECT FINAL PHASE
            </div>
            <div class="card-body">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                {% if needToUpdate == False %}
                    <form action="{% url 'projectfinale' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-12 mb-0">
                                <div id="div_id_scrum_master" class="form-group">
                                    <label for="id_scrum_master" class=" requiredField">
                                        Scrum master<span class="asteriskField">*</span>
                                    </label>
                                    <div class="">
                                        <input type="text" name="scrum_master" value="{{ user.name }}" maxlength="100"
                                               class="textinput textInput form-control"
                                               id="id_scrum_master" readonly>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12 mb-0">
                                {{ formf.project_title|as_crispy_field }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12 mb-0">
                                {{ formf.finale|as_crispy_field }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-8 mb-0 offset-1">
                                <button type="submit" class="btn btn-block font-weight-bold"
                                        style="background: royalblue;color: black; ">Submit Details
                                </button>
                            </div>
                        </div>
                    </form>
                {% else %}
                    {% for data in queryset %}
                        {{ data.finale }}

                        <a href="{% url 'updateFinale' data.id %}" class="btn btn-block font-weight-bold"
                           style="background: royalblue;color: black; ">Update Details
                        </a>
                        <div class="container text-right m-2 p-2">
                            <span class="badge badge-info badge-pill p-2 font-weight-bolder" style="background:powderblue; color:black;">Project Created at: {{ data.created_at }}</span>
                            <span class="badge badge-info badge-pill p-2 font-weight-bolder" style="background:powderblue; color:black;">Project Updated at: {{ data.updated_at }}</span>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>


    </div>

{% endblock %}

projectmanager/templates/project/project_phase1.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %} <title>Phase 1</title>
    {{ form.media }}
    <script type="text/javascript" src="{% static 'tinymce/tinymce.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'django_tinymce/init_tinymce.js' %}"></script>
{% endblock %}


{% block useCss %} {% endblock %}

{% block content %}

    <div class="container p-1">
        <div class="card mt-2">
            <div class="card-header font-weight-bold" style="background:powderblue; color:black;">
                PROJECT PHASE - I
            </div>
            <div class="card-body">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                {% if needToUpdate == False %}
                    <form action="{% url 'projectphase1' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-12 mb-0">
                                <div id="div_id_scrum_master" class="form-group">
                                    <label for="id_scrum_master" class=" requiredField">
                                        Scrum master<span class="asteriskField">*</span>
                                    </label>
                                    <div class="">
                                        <input type="text" name="scrum_master" value="{{ user.name }}" maxlength="100"
                                               class="textinput textInput form-control"
                                               id="id_scrum_master" readonly>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12 mb-0">
                                {{ form1.project_title|as_crispy_field }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12 mb-0">
                                {{ form1.phase1|as_crispy_field }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-8 mb-0 offset-1">
                                <button type="submit" class="btn btn-block font-weight-bold"
                                        style="background: royalblue;color: black; ">Submit Details
                                </button>
                            </div>
                        </div>
                    </form>
                {% else %}
                    {% for data in queryset %}
                        {{ data.phase1 }}

                        <a href="{% url 'updatePhase1' data.id %}" class="btn btn-block font-weight-bold"
                           style="background: royalblue;color: black; ">Update Details
                        </a>
                        <div class="container text-right m-2 p-2">
                            <span class="badge badge-info badge-pill p-2 font-weight-bolder" style="background:powderblue; color:black;">Project Created at: {{ data.created_at }}</span>
                            <span class="badge badge-info badge-pill p-2 font-weight-bolder" style="background:powderblue; color:black;">Project Updated at: {{ data.updated_at }}</span>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>


    </div>

{% endblock %}

projectmanager/templates/project/updateDoc.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %} <title>Synopsis</title>
{{ form.media }}
<script type="text/javascript" src="{% static 'tinymce/tinymce.min.js' %}"></script>
<script type="text/javascript" src="{% static 'django_tinymce/init_tinymce.js' %}"></script>
{% endblock %}


{% block useCss %} {% endblock %}

{% block content %}

    <div class="container p-1">
        <div class="card mt-2">
            <div class="card-header font-weight-bold" style="background:powderblue; color:black;">
                PROJECT SYNOPSIS
            </div>
            <div class="card-body">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-row">
                        <div class="form-group col-md-12 mb-0">
                            {{ form.synopsis|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-8 mb-0 offset-1">
                            <button type="submit" class="btn btn-block font-weight-bold"
                                    style="background: royalblue;color: black; ">Update Details
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>


    </div>

{% endblock %}